---
title: "08-Methylkit"
output: html_document
---

_This is carry over from nb 07 with a more focus on Methylkit_




```{r}
library(methylKit)
```




```{r}
#myobj_07_10x = processBismarkAln(location = file.list_07, sample.id = list("1","2","3","4","5","6","7","8"), assembly = "v081", read.context="CpG", mincov=10, treatment = c(0,0,0,0,1,1,1,1))
```

```{r}
#myobj_07_3x = processBismarkAln(location = file.list_07, sample.id = list("1","2","3","4","5","6","7","8"), assembly = "v081", read.context="CpG", mincov=3, treatment = c(0,0,0,0,1,1,1,1))
```



```{r}
getMethylationStats(myobj_07_3x[[2]],plot=FALSE,both.strands=FALSE)
```

```{r}
getMethylationStats(myobj_07_3x[[8]],plot=TRUE,both.strands=FALSE)
```

```{r}
getCoverageStats(myobj_07_3x[[4]],plot=TRUE,both.strands=FALSE)
```


```{r}
filtered.myobj=filterByCoverage(myobj_07_3x,lo.count=3,lo.perc=NULL,
                                      hi.count=NULL,hi.perc=99.9)

meth_filter=unite(filtered.myobj, destrand=TRUE)

clusterSamples(meth_filter, dist="correlation", method="ward", plot=TRUE)


PCASamples(meth_filter)


```






```{r}
clusterSamples(meth_07_3x, dist="correlation", method="ward", plot=TRUE)
```






```{r}
clusterSamples(meth_07_10x, dist="correlation", method="ward", plot=TRUE)

```


```{r}
myobj_07_3x = processBismarkAln(location = file.list_07, sample.id = list("1","2","3","4","5","6","7","8"), assembly = "v081", read.context="CpG", mincov=3, treatment = c(0,0,0,0,1,1,1,1))
```



```{r}
save(myobj_07_3x, file = "../analyses/myobj_07_3x")

```

```{bash}
zip ../analyses/myobj_07_3x.zip ../analyses/myobj_07_3x
```


```{bash}
unzip ../analyses/myobj_07_3x.zip
```


```{r}
load("analyses/myobj_07_3x")
```




```{r}
tiles=tileMethylCounts(myobj_07_3x,win.size=1000,step.size=1000)
head(tiles[[1]],3)
```







```{r}
meth_07_3x=unite(myobj_07_3x)
```





```{r}
myDiff=calculateDiffMeth(meth_filter,mc.cores=2)

```



```{r}
# get hyper methylated bases
myDiff25p.hyper=getMethylDiff(myDiff,difference=25,qvalue=0.01,type="hyper")
#
# get hypo methylated bases
myDiff25p.hypo=getMethylDiff(myDiff,difference=25,qvalue=0.01,type="hypo")
#
#
# get all differentially methylated bases
myDiff25p=getMethylDiff(myDiff,difference=25,qvalue=0.01)





```




```{r}
write.table(myDiff25p, file = "../analyses/myDiff25p.tab", sep = "\t")
```


---
# Taking the DMLs to a bed

```{r}
library(readr)
myDiff25p <- read_csv("../analyses/myDiff25p.csv")
 
```


```{r}
head(myDiff25p)
```


```{r}
library(tidyverse)
```



```{r}
dml1010 <-  mutate(myDiff25p, start = start -1, end = end + 1) %>% select(chr, start, end, meth.diff) %>% 
  mutate_if(is.numeric, as.integer) 


write_delim(dml1010, "../analyses/dml010.bed",  delim = '\t', col_names = FALSE)
```



