---
title: "Tiles"
output: html_document
---




```{bash}
unzip ../analyses/myobj_07_3x.zip
```


```{r}
load("analyses/myobj_07_3x")
```




```{r}
# Function
tileit <- function(object, win.size=50, step.size=50, cov.bases=3) {
  g.meth <- as(object,"GRanges")
  chrs <- as.character(unique(seqnames(g.meth)))
  grl <- split(g.meth, seqnames(g.meth))
  max.length <- max(end(grl))
  numTiles <- floor((max.length - (win.size - step.size))/step.size) + 1
  starts <- unlist(sapply(numTiles,function(x) 1+0:(x-1)*step.size))
  ranges <- IRanges(start=starts, width=rep(win.size,length(starts)))
  all.wins <- GRanges(seqnames=Rle(chrs, numTiles), ranges=ranges)
  rcounts <- regionCounts(object, all.wins, 0, strand.aware=FALSE)
  rcounts.filtered <- rcounts[rcounts$coverage >= cov.bases, ]
  return(rcounts.filtered)
}

# Code to run function on methylKitList
new.list <- lapply(myobj_07_3x, tileit)
myobj.tiled <- new("methylRawList", new.list, treatment=myobj_07_3x@treatment)
```


```{r}
filtered.myobj=filterByCoverage(myobj.tiled,lo.count=3,lo.perc=NULL,
                                      hi.count=NULL,hi.perc=99.9)

meth_filter=unite(filtered.myobj, destrand=TRUE)

clusterSamples(meth_filter, dist="correlation", method="ward", plot=TRUE)


PCASamples(meth_filter)


```






```{r}
myDiff=calculateDiffMeth(meth_filter,mc.cores=4)

```



```{r}
# get hyper methylated bases
myDiff25p.t.hyper=getMethylDiff(myDiff,difference=25,qvalue=0.01,type="hyper")
#
# get hypo methylated bases
myDiff25p.t.hypo=getMethylDiff(myDiff,difference=25,qvalue=0.01,type="hypo")
#
#
# get all differentially methylated bases
myDiff25p.t=getMethylDiff(myDiff,difference=25,qvalue=0.01)





```




```{r}
write.table(myDiff25p.t, file = "../analyses/myDiff25p.tile.csv", sep = ",")
```


---
# Taking the DMLs to a bed

```{r}
library(readr)
myDiff25p.tile <- read_csv("../analyses/myDiff25p.tile.csv")
 
```


```{r}
head(myDiff25p.tile)
```


```{r}
library(tidyverse)
```



```{r}
dml1010.tile <-  select(myDiff25p.tile, chr, start, end, meth.diff) %>% 
  mutate_if(is.numeric, as.integer) 


write_delim(dml1010.tile, "../analyses/dml010.tile.bed",  delim = '\t', col_names = FALSE)
```


