---
title: "09-methylkit-dml"
output: html_document
---


This notebook was started running Rstudio server on roadrunner - Microsoft version of R.

Running Bismark with  –score_min L,0,-0.6 
Run by Sam

https://github.com/RobertsLab/resources/issues/430


```
```


output
http://gannet.fish.washington.edu/Atumefaciens/20181015_oly_WGBSseq_v081/





## Downloading de-duplicated bams.


```{bash}

```


```{bash}
pwd
```


http://gannet.fish.washington.edu/Atumefaciens/20181015_oly_WGBSseq_v081/2_CGATGT_L001_R1_001_trimmed_bismark_bt2.deduplicated.bam

```{bash}
curl -O  http://gannet.fish.washington.edu/Atumefaciens/20181015_oly_WGBSseq_v081/1_ATCACG_L001_R1_001_trimmed_bismark_bt2.deduplicated.sorted.bam
curl -O  http://gannet.fish.washington.edu/Atumefaciens/20181015_oly_WGBSseq_v081/2_CGATGT_L001_R1_001_trimmed_bismark_bt2.deduplicated.sorted.bam
curl -O  http://gannet.fish.washington.edu/Atumefaciens/20181015_oly_WGBSseq_v081/3_TTAGGC_L001_R1_001_trimmed_bismark_bt2.deduplicated.sorted.bam
curl -O  http://gannet.fish.washington.edu/Atumefaciens/20181015_oly_WGBSseq_v081/4_TGACCA_L001_R1_001_trimmed_bismark_bt2.deduplicated.sorted.bam
curl -O  http://gannet.fish.washington.edu/Atumefaciens/20181015_oly_WGBSseq_v081/5_ACAGTG_L001_R1_001_trimmed_bismark_bt2.deduplicated.sorted.bam
curl -O  http://gannet.fish.washington.edu/Atumefaciens/20181015_oly_WGBSseq_v081/6_GCCAAT_L001_R1_001_trimmed_bismark_bt2.deduplicated.sorted.bam
curl -O  http://gannet.fish.washington.edu/Atumefaciens/20181015_oly_WGBSseq_v081/7_CAGATC_L001_R1_001_trimmed_bismark_bt2.deduplicated.sorted.bam
curl -O  http://gannet.fish.washington.edu/Atumefaciens/20181015_oly_WGBSseq_v081/8_ACTTGA_L001_R1_001_trimmed_bismark_bt2.deduplicated.sorted.bam
```



```{bash}
ls ../data_1102
```


```{r}
file.list_11=list('../data_1102/1_ATCACG_L001_R1_001_trimmed_bismark_bt2.deduplicated.sorted.bam',
                 '../data_1102/2_CGATGT_L001_R1_001_trimmed_bismark_bt2.deduplicated.sorted.bam',
                 '../data_1102/3_TTAGGC_L001_R1_001_trimmed_bismark_bt2.deduplicated.sorted.bam',
                 '../data_1102/4_TGACCA_L001_R1_001_trimmed_bismark_bt2.deduplicated.sorted.bam',
                 '../data_1102/5_ACAGTG_L001_R1_001_trimmed_bismark_bt2.deduplicated.sorted.bam',
                 '../data_1102/6_GCCAAT_L001_R1_001_trimmed_bismark_bt2.deduplicated.sorted.bam',
                 '../data_1102/7_CAGATC_L001_R1_001_trimmed_bismark_bt2.deduplicated.sorted.bam',
                 '../data_1102/8_ACTTGA_L001_R1_001_trimmed_bismark_bt2.deduplicated.sorted.bam'
)
```





```{r}
library(methylKit)
```



```{r, eval = FALSE}
myobj_09 = processBismarkAln(location = file.list_11, sample.id = list("1","2","3","4","5","6","7","8"), assembly = "v081", read.context="CpG", mincov=2, treatment = c(0,0,0,0,1,1,1,1))
```

```{r, eval = FALSE}
save(myobj_09, file = "../analyses/myobj_09")

```


```{r}
#load("../analyses/myobj_09")
```





```{r}
getMethylationStats(myobj_09[[2]],plot=FALSE,both.strands=FALSE)
```

```{r}
getMethylationStats(myobj_09[[8]],plot=TRUE,both.strands=FALSE)
```

```{r}
getCoverageStats(myobj_09[[4]],plot=TRUE,both.strands=FALSE)
```


```{r}
filtered.myobj=filterByCoverage(myobj_09,lo.count=3,lo.perc=NULL,
                                      hi.count=NULL,hi.perc=99.9)

meth_filter=unite(filtered.myobj, destrand=TRUE)

clusterSamples(meth_filter, dist="correlation", method="ward", plot=TRUE)


PCASamples(meth_filter)


```




```{r}
myDiff=calculateDiffMeth(meth_filter,mc.cores=2)

```



```{r}
# get hyper methylated bases
myDiff25p.hyper=getMethylDiff(myDiff,difference=25,qvalue=0.01,type="hyper")
#
# get hypo methylated bases
myDiff25p.hypo=getMethylDiff(myDiff,difference=25,qvalue=0.01,type="hypo")
#
#
# get all differentially methylated bases
myDiff25p=getMethylDiff(myDiff,difference=25,qvalue=0.01)





```




```{r}
write.table(myDiff25p, file = "../analyses/myDiff25p.tab", sep = "\t")
```



